### ISSUE TITLE
can not run !!!

### ISSUE THREAD

**Issue by longcoolman** [LitingLin/SwinTrack#33]
python main.py SwinTrack Tiny --output_dir /home/lfm/swintrack/out --num_workers 4

Traceback (most recent call last):
  File "main.py", line 6, in <module>
    main(os.path.dirname(__file__))
  File "/home/lfm/swintrack/core/entry/main.py", line 104, in main
    entry(args)
  File "/home/lfm/swintrack/core/entry/entry.py", line 68, in entry
    build_and_run(runtime_vars, config, wandb_instance)
  File "/home/lfm/swintrack/core/entry/build_and_run.py", line 21, in build_and_run
    run = build(runtime_vars, network_config, global_synchronized_rng, local_rng, wandb_instance)
  File "/home/lfm/swintrack/core/run/builder.py", line 312, in build
    model, pseudo_data_generator, running_tasks, global_event_dispatcher, default_logger, num_epochs = build_running_tasks(runtime_vars, config, global_rng, local_rng, wandb_instance)
  File "/home/lfm/swintrack/core/run/builder.py", line 262, in build_running_tasks
    _build_data_loaders(runtime_vars, branch_config, data_config, config, global_rng, local_rng, building_context)
  File "/home/lfm/swintrack/core/run/builder.py", line 180, in _build_data_loaders
    data_loader, host_data_pipelines = build_data_source(  # host_data_pipelines = [ { type: instance } ]
  File "/home/lfm/swintrack/data/tracking/builder.py", line 8, in build_data_source
    data_pipelines = build_siamfc_data_source(data_config, runtime_vars, config, global_synchronized_rng, local_rng, event_register, context)
  File "/home/lfm/swintrack/data/tracking/methods/SiamFC/builders/source.py", line 16, in build_siamfc_data_source
    dataset, worker_init_fn = build_siamfc_dataset(sampling_config, dataset_config, data_processor,
  File "/home/lfm/swintrack/data/tracking/methods/SiamFC/builders/components/dataset.py", line 16, in build_siamfc_dataset
    datasets, dataset_parameters = build_datasets(dataset_config)
  File "/home/lfm/swintrack/data/tracking/methods/_common/builders/build_datasets.py", line 23, in build_datasets
    datasets, dataset_parameters = build_dataset_from_config_distributed_awareness(dataset_config, _customized_dataset_parameter_handler)
  File "/home/lfm/swintrack/data/utils/dataset.py", line 8, in build_dataset_from_config_distributed_awareness
    return build_datasets_from_config(config, user_defined_parameters_handler)
  File "/home/lfm/swintrack/datasets/easy_builder/builder.py", line 148, in build_datasets_from_config
    return build_datasets(config, unknown_parameter_handler)
  File "/home/lfm/swintrack/datasets/easy_builder/builder.py", line 120, in build_datasets
    seed = seed_class(root_path=path)
  File "/home/lfm/swintrack/datasets/SOT/seed/LaSOT.py", line 9, in __init__
    super(LaSOT_Seed, self).__init__('LaSOT', root_path, data_split, 2)
  File "/home/lfm/swintrack/datasets/base/factory_seed.py", line 11, in __init__
    assert root_path is not None and len(root_path) > 0
AssertionError

**Comment by mark0113** [comment]
Same question anyway. Have u fixed it yet? Many thanks.

**Comment by Torch-HXM** [comment]
If you want to evaluate on got-10k only,you can change SwinTrack/datasets/easy_builder/builder.py like this:(about 147 lines)

def build_datasets_from_config(config: dict, unknown_parameter_handler=_default_unknown_parameter_handler):
    with open(os.path.join(os.path.dirname(__file__), 'defaults.yaml'), 'rb') as fid:
        default = yaml.safe_load(fid)
    default = default['datasets']
    dataset_config = merge_config(default, config['datasets'])
    #config['datasets'] = dataset_config    #修改
    config['datasets'] = {'GOT10k': {'type': 'SOT', 'splits': ['val', 'test']}}
    print('>>>config datasets:',config['datasets'])
    return build_datasets(config, unknown_parameter_handler)

Then you can evaluate only on got-10k.
Don't forget to add the absolute path of got-10k to SwinTrack/path.yaml

**Comment by AlanHuangKP** [comment]
> Firstly you should have a dataset.For example you have the GOT-10K dataset. If you want to evaluate on got-10k only,you can change SwinTrack/datasets/easy_builder/builder.py like this:(about 147 lines)
> 
> def build_datasets_from_config(config: dict, unknown_parameter_handler=_default_unknown_parameter_handler): with open(os.path.join(os.path.dirname(**file**), 'defaults.yaml'), 'rb') as fid: default = yaml.safe_load(fid) default = default['datasets'] dataset_config = merge_config(default, config['datasets']) #config['datasets'] = dataset_config #修改 config['datasets'] = {'GOT10k': {'type': 'SOT', 'splits': ['val', 'test']}} print('>>>config datasets:',config['datasets']) return build_datasets(config, unknown_parameter_handler)
> 
> Then you can evaluate only on got-10k. Don't forget to add the absolute path of got-10k to SwinTrack/path.yaml

Hi, if I want to evaluate on LaSOT, where shuld I change?
